version: "3"
services:
  app:
    container_name: bike-app
    image: latest123/bike-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'